sudo: false
language: python
cache: pip
git:
  depth: 1

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - env: DJANGO="Django>=2.0,<2.1"
      python: "2.7"
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
      python: "2.7"
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
      python: "3.4"
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
      python: "3.5"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

before_install: pip install --upgrade pip

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install $DJANGO mock-django==0.6.9 django-js-asset
# command to run tests, e.g. python setup.py test
script: cd tests/ && ./runtests.sh
