dist: xenial
language: python
cache: pip
git:
  depth: 1

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"

env:
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==2.0.*"
  - DJANGO="Django==2.1.*"
  - DJANGO="Django==2.2.*"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - env: DJANGO="Django==1.11.*"
      python: "3.8"
    - env: DJANGO="Django==2.0.*"
      python: "3.8"
    - env: DJANGO="Django==2.1.*"
      python: "3.8"
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
      python: "3.5"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

before_install: pip install --upgrade pip

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install $DJANGO mock-django==0.6.9 django-js-asset
# command to run tests, e.g. python setup.py test
script: cd tests/ && ./runtests.sh
